name: Setup Java and Gradle
description: A reusable workflow to set up Java and Gradle environment.
runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: corretto
        java-version: '17'
        cache: 'gradle'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        gradle-home-cache-includes: |
          caches
          notifications
        gradle-home-cache-cleanup: true
